### ISSUE TITLE
error with test_flownet_2012.py/test_flownet_2015.py

### ISSUE THREAD

**Issue by yasser-taha** [vt-vl-lab/DF-Net#11]
I was able to get the same results for the depth net by running the following commands mentioned in the repo:
`python test_kitti_depth.py --dataset_dir=/path/to/your/data --output_dir=/path/to/save/your/prediction --ckpt_file=/DF-Net-master/pretrained/dfnet - --split="test"`
and
`python kitti_eval/eval_depth.py --pred_file=/path/to/your/prediction --split="test"` 

However when I run the test Flownet command on kitti 2012 OR on kitti 2015:
`python test_flownet_2012.py --dataset_dir=/path/to/your/data --ckpt_file=/DF-Net-master/pretrained/unflow_pre
`

I get the following error:

```Traceback (most recent call last):
  File "test_flownet_2015.py", line 131, in <module>
    tf.app.run()
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test_flownet_2015.py", line 90, in main
    saver.restore(sess, FLAGS.ckpt_file)
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Correlation' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: flownet_c/Correlation = Correlation[kernel_size=1, max_displacement=20, pad=20, stride_1=1, stride_2=2](flownet_c_features/conv3/leaky_relu/Maximum, flownet_c_features/conv3_1/leaky_relu/Maximum)]]

Caused by op 'flownet_c/Correlation', defined at:
  File "test_flownet_2015.py", line 131, in <module>
    tf.app.run()
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test_flownet_2015.py", line 78, in main
    pred_flows = flownet(im1_pl, im2_pl, flownet_spec='C')
  File "/system/user/taha/pycharmprojects/DF-Net-master/core/UnFlow/src/e2eflow/core/flownet.py", line 86, in flownet
    scoped_block(reuse)
  File "/system/user/taha/pycharmprojects/DF-Net-master/core/UnFlow/src/e2eflow/core/flownet.py", line 43, in scoped_block
    channel_mult=channel_mult)
  File "/system/user/taha/pycharmprojects/DF-Net-master/core/UnFlow/src/e2eflow/core/flownet.py", line 231, in flownet_c
    pad=20, kernel_size=1, max_displacement=20, stride_1=1, stride_2=2)
  File "/system/user/taha/pycharmprojects/DF-Net-master/core/UnFlow/src/e2eflow/ops.py", line 64, in correlation
    return _correlation_module.correlation(first, second, **kwargs)[0]
  File "<string>", line 49, in correlation
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/system/user/taha/pycharmprojects/DF-Net-master/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Correlation' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: flownet_c/Correlation = Correlation[kernel_size=1, max_displacement=20, pad=20, stride_1=1, stride_2=2](flownet_c_features/conv3/leaky_relu/Maximum, flownet_c_features/conv3_1/leaky_relu/Maximum)]]
```
Any ideas on how to fix it?
@Yuliang-Zou

**Comment by Yuliang-Zou** [comment]
Did you successfully install the CUDA op according to the instructions?

**Comment by yasser-taha** [comment]
The issue was solved when I changed cudnn 6.0 to 5.1.

**Comment by vikyzeng** [comment]
> The issue was solved when I changed cudnn 6.0 to 5.1.

Sorry to bother！ I have same question as you did before.  It worked with test_kitti_depth.py, but got problem with test_flownet.py

`$ python test_flownet_2015.py 
/home/zengyihan/Yihan/DF-Net-master/core/UnFlow/ops/backward_warp_op.so
/home/zengyihan/Yihan/DF-Net-master/core/UnFlow/ops/downsample_op.so
/home/zengyihan/Yihan/DF-Net-master/core/UnFlow/ops/correlation_op.so
/home/zengyihan/Yihan/DF-Net-master/core/UnFlow/ops/forward_warp_op.so
WARNING:tensorflow:From test_flownet_2015.py:80: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
2020-02-19 12:55:38.268082: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2020-02-19 12:55:38.268103: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2020-02-19 12:55:38.268107: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2020-02-19 12:55:38.268110: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2020-02-19 12:55:38.268113: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1117, in _run_fn
    self._extend_graph()
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1166, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Correlation' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: flownet_c/Correlation = Correlation[kernel_size=1, max_displacement=20, pad=20, stride_1=1, stride_2=2](flownet_c_features/conv3/leaky_relu/Maximum, flownet_c_features/conv3_1/leaky_relu/Maximum)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_flownet_2015.py", line 131, in <module>
    tf.app.run()
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test_flownet_2015.py", line 90, in main
    saver.restore(sess, FLAGS.ckpt_file)
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Correlation' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: flownet_c/Correlation = Correlation[kernel_size=1, max_displacement=20, pad=20, stride_1=1, stride_2=2](flownet_c_features/conv3/leaky_relu/Maximum, flownet_c_features/conv3_1/leaky_relu/Maximum)]]

Caused by op 'flownet_c/Correlation', defined at:
  File "test_flownet_2015.py", line 131, in <module>
    tf.app.run()
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test_flownet_2015.py", line 78, in main
    pred_flows = flownet(im1_pl, im2_pl, flownet_spec='C')
  File "/home/zengyihan/Yihan/DF-Net-master/core/UnFlow/src/e2eflow/core/flownet.py", line 86, in flownet
    scoped_block(reuse)
  File "/home/zengyihan/Yihan/DF-Net-master/core/UnFlow/src/e2eflow/core/flownet.py", line 43, in scoped_block
    channel_mult=channel_mult)
  File "/home/zengyihan/Yihan/DF-Net-master/core/UnFlow/src/e2eflow/core/flownet.py", line 231, in flownet_c
    pad=20, kernel_size=1, max_displacement=20, stride_1=1, stride_2=2)
  File "/home/zengyihan/Yihan/DF-Net-master/core/UnFlow/src/e2eflow/ops.py", line 65, in correlation
    return _correlation_module.correlation(first, second, **kwargs)[0]
  File "<string>", line 49, in correlation
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/zengyihan/anaconda3/envs/dfnet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Correlation' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: flownet_c/Correlation = Correlation[kernel_size=1, max_displacement=20, pad=20, stride_1=1, stride_2=2](flownet_c_features/conv3/leaky_relu/Maximum, flownet_c_features/conv3_1/leaky_relu/Maximum)]]
`



My environment is CUDA8.0, cudnn5.1.10. So I really confused. Can I know what else did you do to fix that problem？ By the way, my code in ./core/UnFlow/src/e2eflow/ops.py is 

`
        cuda_lib64_path_arg = "-L /usr/local/cuda-8.0/lib64"
        nvcc_cmd = "nvcc -std=c++11 -c  -o {} -I {} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -I $/usr/local/cuda-8.0/include"
        nvcc_cmd = nvcc_cmd.format(" ".join([fn_cu_o, fn_cu_cc]),
                                   tf_inc)
        subprocess.check_output(nvcc_cmd, shell=True)

        gcc_cmd = "{} -std=c++11 -shared -o {} -I {} -fPIC -lcudart -D GOOGLE_CUDA=1 {}"
        gcc_cmd = gcc_cmd.format('g++4.9',
                                " ".join([fn_so, fn_cu_o, fn_cc]),
                                 tf_inc,
                                 cuda_lib64_path_arg)
        subprocess.check_output(gcc_cmd, shell=True)`

Is it any problem with that？

**Comment by vikyzeng** [comment]
> Did you successfully install the CUDA op according to the instructions?

Sorry to bother you！What instructions do you mean？

**Comment by vikyzeng** [comment]
> Did you successfully install the CUDA op according to the instructions?

Actually I cannot compile myself, so I directly copy the compiled ops you provided in another issue, will it cause problems？
