### ISSUE TITLE
version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by PoojaGhaywate** [vt-vl-lab/DF-Net#14]
Hi,
Python=2.7
Ubuntu 14.04

I was following the instructions in read me file and got this errors

coesip@coesip-HP-Z230-SFF-Workstation:~$ cd Desktop/DF-Net-master/
coesip@coesip-HP-Z230-SFF-Workstation:~/Desktop/DF-Net-master$ python train_df.py --dataset_dir=/home/coesip/Desktop/DF-Net-master/dataset --checkpoint_dir=/home/coesip/Desktop/DF-Net-master
Traceback (most recent call last):
  File "train_df.py", line 6, in <module>
    from core import DFLearner
  File "/home/coesip/Desktop/DF-Net-master/core/__init__.py", line 2, in <module>
    from .DFLearner import DFLearner
  File "/home/coesip/Desktop/DF-Net-master/core/DFLearner.py", line 9, in <module>
    from .BaseLearner import BaseLearner
  File "/home/coesip/Desktop/DF-Net-master/core/BaseLearner.py", line 10, in <module>
    from .nets import *
  File "/home/coesip/Desktop/DF-Net-master/core/nets.py", line 7, in <module>
    from .utils import flow_inverse_warp
  File "/home/coesip/Desktop/DF-Net-master/core/utils.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/home/coesip/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "/home/coesip/anaconda2/lib/python2.7/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/home/coesip/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "/home/coesip/anaconda2/lib/python2.7/site-packages/matplotlib/path.py", line 21, in <module>
    from . import _path, rcParams
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/coesip/anaconda2/lib/python2.7/site-packages/matplotlib/_path.so)
 How to solve this?

**Comment by Yuliang-Zou** [comment]
Seems to be something related to `matplotlib`, but not this project.
